---
title: "ch3"
author: "Christoper Chan"
date: "November 20, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MASS)
library(ISLR)
library(ggplot2)
print('done')
```

Load in dataframe and begin to understand the variables
```{r}
data(Boston)
names(Boston)
head(Boston)
attach(Boston)
```

```{r}
dim(Boston)
```


## 3.6.2
Fit a simple linear regression model to lower status of population (lstat) &median home value (medv)

```{r}
lm.fit <- lm(medv~lstat, data=Boston)
summary(lm.fit)
```

```{r}
confint(lm.fit)
```

```{r}
predict(lm.fit, data.frame(lstat=c(5,10, 15)), interval='confidence')
```

```{r}
coef(lm.fit)
```

```{r}
ggplot(Boston, aes(lstat, medv)) +
  geom_point() +
  labs('lstat', 'medv', title = 'linear regression of lstat and medv') +
  geom_abline(intercept = 34.55, slope = -0.95, color = '#E41A1C')
```


```{r}
ggplot(lm.fit, aes(predict(lm.fit), residuals(lm.fit))) +
  geom_point()
```

```{r}
ggplot(lm.fit, aes(predict(lm.fit), rstudent(lm.fit))) +
  geom_point()
```

## 3.6.3
```{r}
mlm.fit = lm(medv~lstat + age, data=Boston)
summary(mlm.fit)
```

Linear regression model with y = medv and x = the rest of the variables
```{r}
all_lm.fit = lm(medv ~ ., data = Boston)
summary(all_lm.fit)
```

## 3.6.4
```{r}
summary(lm(medv~lstat*age, data=Boston))

```

## 3.6.5
```{r}
lm.fit2 <- lm(medv~lstat + I(lstat^2))
summary(lm.fit2)
```

```{r}
anova(lm.fit, lm.fit2)
```

```{r}
par(mfrow <- c(2,2))
plot(lm.fit2)
```

```{r}
lm.fit6 <- lm(medv~poly(lstat, 6))
summary(lm.fit6)
```

## 3.6.6
```{r}
fix(Carseats)
names(Carseats)
attach(Carseats)
```

```{r}
lm.fit <- lm(Sales~. +Income:Advertising + Price:Age, data=Carseats)
summary(lm.fit)
```

```{r}
contrasts(ShelveLoc)
```

## 3.6.7
```{r}
LoadLibraries <- function(){
  library(ISLR)
  library(MASS)
  library(tidyverse)
  print('Loading essential libraries')
}
```

# 3.7 Exercises
```{r}
LoadLibraries()
```

#### 1
Null hypothesis:














