---
title: "ch4_labs"
author: "Christopher Chan"
date: "January 8, 2019"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(ISLR)
```

##4.6.1
```{r}
dim(Smarket)
head(Smarket)
summary(Smarket)
```

```{r}
cor(Smarket[, -9])
```

```{r, message=FALSE}
attach(Smarket)
plot(Volume)
```

##4.6.2
```{r}
glm_fits <- glm(Direction~.-Year-Today, Smarket, family=binomial)
summary(glm_fits)
coef(glm_fits)
```

Creating the prediction for based on the glm we created. We create a vector that is length $n$ of "Down". If the prob is greater than 0.5 we set the corresponding glm_pred[i] to "Up"
```{r}
glm_probs <- predict(glm_fits, type='response')
glm_probs[1:10]

glm_pred <- rep('Down', 1250)
glm_pred[glm_probs>0.5] = 'Up'
```

```{r}
table(glm_pred, Direction)

#These yield the same value.
(145+507)/1250
mean(Direction == glm_pred)
```

Creating the training dataset. We are only using the observations that occur in year 2005.
```{r}
train <- Smarket %>%
    filter(Year < 2005)
test <- Smarket %>%
    filter(Year == 2005)

dim(test)
```


```{r}
glm_fits2005 <- glm(Direction~Lag1+Lag2+Lag3+Lag4+Lag5+Volume, data=train, family=binomial)

glm_probs2005 <- predict(glm_fits2005, test, type='response')

length(glm_probs2005)
```

```{r}
glm_pred2005 <- rep("Down", 252)
glm_pred2005[glm_probs2005 > 0.5] = 'Up'

table(glm_pred2005, test[,9])

mean(glm_pred2005 == test[,9])
mean(glm_pred2005 != test[,9])
```

```{r}
glm_fits2 <- glm(Direction~Lag1+Lag2, train, family=binomial)

glm_probs2 <- predict(glm_fits2, test, type='response')

glm_pred2 <- rep('Down', 252)
glm_pred2[glm_probs2 < 0.5] = 'Up'

table(glm_pred2, test[,9])

mean(glm_pred2 == test[,9])
```
























